INSERT INTO et_category(category_id, category_title, category_description) VALUES('CAT0001','Food','Food Related Expenses');
INSERT INTO et_category(category_id, category_title, category_description) VALUES('CAT0002','Rent','Rent Related Expenses');
INSERT INTO et_category(category_id, category_title, category_description) VALUES('CAT0003','Travel','Travel Related Expenses');
INSERT INTO et_category(category_id, category_title, category_description) VALUES('CAT0004','Payment','Payment Related Expenses');
INSERT INTO et_category(category_id, category_title, category_description) VALUES('CAT0005','Investment','Investment Related Expenses');
INSERT INTO et_category(category_id, category_title, category_description) VALUES('CAT0006','Entertainment','Entertainment Related Expenses');
INSERT INTO et_category(category_id, category_title, category_description) VALUES('CAT0007','Medical','Medical Related Expenses');
INSERT INTO et_category(category_id, category_title, category_description) VALUES('CAT0008','Loans','Loans Related Expenses');
INSERT INTO et_category(category_id, category_title, category_description) VALUES('CAT0009','Bill Payments','Bill Related Expenses');
INSERT INTO et_category(category_id, category_title, category_description) VALUES('CAT00010','Education','Education Related Expenses');
INSERT INTO et_category(category_id, category_title, category_description) VALUES('CAT00011','Application and Software','Software Related Expenses');
INSERT INTO et_category(category_id, category_title, category_description) VALUES('CAT00012','Insurance','Insurance Related Expenses');
INSERT INTO et_category(category_id, category_title, category_description) VALUES('CAT00013','Fuel','Fuel Related Expenses');
INSERT INTO et_category(category_id, category_title, category_description) VALUES('CAT00014','Miscellaneous','Miscellaneous Expenses');
COMMIT;